package carlo.api;

import java.awt.*;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class ApiManager {
    public static final String VEHICLE_ID = "vehicle_id";
    public static final String VEHICLE_MAKE = "vehicle_make";
    public static final String VEHICLE_MODEL = "vehicle_model";
    public static final String VEHICLE_YEAR = "vehicle_year";
    public static final String ACCESS_TOKEN = "access_token";
    public static final String AUTH_CLIENT = "auth_client";
    public static final String AUTH = "auth";
    public static final String LATITUDE = "latitude";
    public static final String LONGITUDE = "longitude";
    public static final String VEHICLE_IDS = "vehicle_ids";
    public static final String ODOMETER = "odometer";
    public static final String VIN = "vin";
    public static final String RANGE_PERCENT = "range_percent";
    public static final String RANGE_RADIUS = "radius";
    public static final String RANGE_AMOUNT = "product_amount";
    public static final String ACTION_MSG = "status_msg";
    public static final String IS_ELECTRIC = "is_electric";
    public static final String SUCCESSFUL_ACTION = "successful_action";
    public static final String ERROR_MSG = "error_msg";
    public static final String ERROR_CODE = "error_code";
    public static final String USER = "user";
    public static final String PERMISSIONS = "permissions";
    public static final String BATCH = "batch";
    public static final List<String> BATCH_ARRAY_ALL = Arrays.asList("/location", "/odometer", "/attributes");
    public static final String SELECTION_BATCH = "selection";
    public static final String REFRESH_TOKEN = "refresh_token";
    public static final String FIRST_NAME = "first_name";
    public static final String SECOND_NAME = "first_name";
    public static final String EMAIL = "email";
    public static final String PHONE = "phone";

    public static final String OIL = "oil";
    public static final String CAR_MARKET_VALUE_ENDPOINT = "car_market_value";
    public static final String MARKET_VALUE_ENDPOINT = "endpoint_market_value";
    public static final String CAR_ATTRIBUTE_ENDPOINT = "endpoint_car_attribute";
    public static final String GET_USER_ENDPOINT = "endpoint_get_user";
    public static final String IS_ELECTRIC_ENDPOINT = "endpoint_is_electric";
    public static final String UNLOCK_ENDPOINT = "endpoint_unlock";
    public static final String LOCK_ENDPOINT = "endpoint_lock";
    public static final String VEHICLE_RANGE_ENDPOINT = "endpoint_vehicle_range";
    public static final String VIN_ENDPOINT = "endpoint_vin";
    public static final String ODOMETER_ENDPOINT = "endpoint_odometer";
    public static final String BATCH_ENDPOINT = "endpoint_batch";
    public static final String PERMISSIONS_ENDPOINT = "endpoint_permissions";
    public static final String VALIDATE_ENDPOINT = "endpoint_validate";
    public static final String REFRESH_TOKEN_ENDPOINT = "endpoint_refresh_token";
    public static final String GET_VEHICLES_ENDPOINT = "endpoint_get_vehicles";
    public static final String OIL_ENDPOINT = "endpoint_oil";
    public static final String LOCATION_ENDPOINT = "endpoint_location";
    public static final String GET_ACCESS_TOKEN = "endpoint_get_access";
}
